config/routes.rb
RailsBlackJack::Application.routes.draw do

  root 'welcome#index'

  get 'welcome/index'

  resources :games

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
require 'blackjack'

class GamesController < ApplicationController

  def new

  end

  def create
    @game = Blackjack.new(params[:game]['player_name'])

    render :action => :show
  end

  def show

  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/new.html.erb
<h1>Start new game</h1>

<%= form_for :game, url: games_path do |f| %>
    <p>
      <%= f.label 'Enter your name' %><br>
      <%= f.text_field :player_name %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/games/show.html.erb
<p>
  <strong>Player name</strong>
  <%= @game.player_array[0].name  %>
</p>

<p>
    <strong>Bankroll</strong>
    <%= @game.player_array[0].bankroll  %>
</p>

<%= form_tag('/wager', method: 'get') do %>
    <p>
      <%= label_tag(:wager, 'Wager:') %>
      <%= text_field_tag(:wager) %>
      <%= submit_tag('Wager') %>
    </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlackJack</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
  Hi mom
</p>